# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cards2',
                'doc_host': 'https://hamish-haggerty.github.io',
                'git_url': 'https://github.com/hamish-haggerty/nbdev_cards2',
                'lib_path': 'nbdev_cards2'},
  'syms': { 'nbdev_cards2.core': { 'nbdev_cards2.core.bar': ('core.html#bar', 'nbdev_cards2/core.py'),
                                   'nbdev_cards2.core.foo': ('core.html#foo', 'nbdev_cards2/core.py')}}}