# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'bar']

# %% ../nbs/00_core.ipynb 3
import torch
if torch.cuda.is_available():device='cuda'
else:device='cpu'
# import random
#import os
import numpy as np
# import math

# %% ../nbs/00_core.ipynb 4
def foo(): pass

# %% ../nbs/00_core.ipynb 5
def bar():
    
    return 'hi'
